email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: realTheSave
github_username:  thesave86

# Build settings
theme: minima
plugins:
  - jekyll-feed

menu_items:
  - name: Publications
    link: "/publications"
  - name: Projects
    link: "/projects"
  - name: Activities
    link: "/activities"
  - name: Teaching
    link: "/teaching"
  - name: Thesis/Research Ideas
    link: "/ideas"
  - name: About
    link: "/about"