email: saverio.giallorenzo[at]gmail.com
baseurl: "https://saveriogiallorenzo.com"
url: "https://saveriogiallorenzo.com"
github_username: thesave

markdown: kramdown

# Build settings
theme: minima
plugins:
  - jekyll-feed

menu_items:
  - name: Publications
    link: "/publications"
  - name: Projects
    link: "/projects"
  - name: Activities
    link: "/activities"
  - name: Teaching
    link: "/teaching"
  - name: Thesis/Research Ideas
    link: "/ideas"
  - name: About
    link: "/about"